### ISSUE TITLE
Data not availible

### ISSUE THREAD

**Issue by mrgloom** [choosehappy/public#1]
Data ( http://gleason.case.edu/webdata/jpi-dl-tutorial/epi.tgz ) for this tutorial seems not availible http://www.andrewjanowczyk.com/use-case-2-epithelium-segmentation/

And looks like here is only part of data:
https://community.topcoder.com/longcontest/?module=ViewProblemStatement&rd=16950&pm=14622

**Comment by choosehappy** [comment]
where did you find this link? i thought i had updated all of them after the
machine died

the correct set is here: http://www.andrewjanowczyk.com/deep-learning/

**Comment by mrgloom** [comment]
Great!

Link in this post: http://www.andrewjanowczyk.com/use-case-2-epithelium-segmentation/
`The data and the associated masks are located here (336M).`
