### ISSUE TITLE
receiving black images in Humpty_Dumpty.m

### ISSUE THREAD

**Issue by Suvi-dha** [choosehappy/public#3]
Hi, I read yopur blog post on your website and read that old svs files having odd compression technique prevents imread function to read the slides correctl, hence openslide may be used to do read the svs files in this case. 

I changed the code in PagedTiffAdapter.m in order to read my slide image through openslide. But, I am  unable to do run the code correctly. 
Would  you tell me what and where do I have to make changes if I read my file through openslide.

**Comment by choosehappy** [comment]
sorry, i don't use this code anymore. the imagemagik convert approach discussed on the blog as my preferred method. have you tried it? if you really want to use matlab + openslide, i'd suggest just using 2 for loops and avoiding the PagedTiffAdapter approach
